#HTTP
server {
    listen 80;
    server_name cubedave.ch;
    return 301 https://$host$request_uri;
}

# HTTPS
server {    
    listen 443 ssl;
    server_name cubedave.ch;

    ssl_certificate /etc/letsencrypt/live/cubedave.ch/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cubedave.ch/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
 
    location /docs {
        proxy_pass http://fastapi:8000;
    }

    location /openapi.json {
        proxy_pass http://fastapi:8000;
    }

    location /api/ {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
