services:
  fastapi:
    image: fastapi
  nginx-svelte:
    image: nginx-svelte-local
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=david.rometsch@edu.teko.ch
    volumes:
      - letsencrypt:/etc/letsencrypt # certbot stores certs here, persists across restarts

volumes:
  letsencrypt:
